# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Fonting' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Fonting
    pod 'FontAwesomeKit', '~> 2.2.0'
    pod 'CWStatusBarNotification', '~> 2.3'
    pod 'ChameleonFramework'
end
